try different approach

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,31 +1,31 @@
 name: Db-Connector CI
 on: [push, pull_request]
 jobs:
-  database:
-    name: Database
-    runs-on: ubuntu-latest
-    services:
-      mysql:
-        image: mysql:5.7
-        env:
-          MYSQL_ALLOW_EMPTY_PASSWORD: false
-          MYSQL_ROOT_PASSWORD: password
-        ports:
-          - 3306
-        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2.0.0
-
-      - name: Ping MySQL
-        run: |
-          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
-            sleep 1
-          done
-
-      - name: Test MySQL
-        run: |
-          mysql -h"127.0.0.1" -P${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"
+#  database:
+#    name: Database
+#    runs-on: ubuntu-latest
+#    services:
+#      mysql:
+#        image: mysql:5.7
+#        env:
+#          MYSQL_ALLOW_EMPTY_PASSWORD: false
+#          MYSQL_ROOT_PASSWORD: password
+#        ports:
+#          - 3306
+#        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v2.0.0
+#
+#      - name: Ping MySQL
+#        run: |
+#          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
+#            sleep 1
+#          done
+#
+#      - name: Test MySQL
+#        run: |
+#          mysql -h"127.0.0.1" -P${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"
 
   db-connector:
     name: Db-Connector
@@ -82,10 +82,10 @@ jobs:
         run: vendor/bin/phpunit -c $GITHUB_WORKSPACE/phpunit.xml --coverage-text
         env:
           FUNC_TEST_ENV_FILE: .env.github
-          GSD_DB_HOST: mysql
-          GSD_DB_PORT: ${{ job.services.mysql.ports['3306'] }}
-          GSD_DB_USER: root
-          GSD_DB_PASSWORD: password
-          GSD_DB_PERSISTENT: false
-          GSD_DB_SSL: false
+#          GSD_DB_HOST: mysql
 #          GSD_DB_PORT: ${{ job.services.mysql.ports['3306'] }}
+#          GSD_DB_USER: root
+#          GSD_DB_PASSWORD: password
+#          GSD_DB_PERSISTENT: false
+#          GSD_DB_SSL: false
+          CI_PORT: ${{ job.services.mysql.ports['3306'] }}
